# Generated by Django 4.2.23 on 2025-06-26 07:44

from django.db import migrations

def create_ai_user(apps, schema_editor):
    User = apps.get_model('users', 'CustomUser')
    if not User.objects.filter(username='AI_Assistant').exists():
        # 直接设置密码字段为一个不可用密码的哈希值
        # '!' 开头的密码是Django识别为不可用密码的格式
        User.objects.create(
            username='AI_Assistant',
            password='!', # 设置为不可用密码
            is_staff=False,
            is_superuser=False
        )

def remove_ai_user(apps, schema_editor):
    User = apps.get_model('users', 'CustomUser')
    User.objects.filter(username='AI_Assistant').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_ai_user, remove_ai_user),
    ]
