# Generated by Django 4.2.23 on 2025-07-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
    ]
