# Generated by Django 4.2.23 on 2025-07-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_novelchaptercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
